/**
 * `npm run dryrun` — runs the REAL render engine on realistic local inputs and measures the result.
 *
 * Nothing leaves the machine: speech comes from espeak-ng (sentence by sentence, exactly the timing
 * data Kokoro provides), footage is generated by ffmpeg (three shots per scene plus one real video
 * clip), and the output is inspected with ffprobe. It checks what no other test touches: cut rate,
 * audio/video sync, loudness, resolution, captions timing, and how long a render takes, so the
 * CI time limits can be checked against real numbers.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { renderVideo, VERTICAL } from "../src/stages/render";
import { buildChapters } from "../src/stages/publish";

const OUT = path.resolve("dryrun");
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });
const run = (cmd: string, args: string[]) => execFileSync(cmd, args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
const probe = (f: string, entries: string) =>
  run("ffprobe", ["-v", "error", "-show_entries", entries, "-of", "default=nw=1:nk=1", f]).trim().split("\n");
const dur = (f: string) => Number(probe(f, "format=duration")[0]);

const NARRATION = [
  "In 1908 an engineer decided that a steel cable could break the sound barrier. Nobody asked him to. He did it anyway.",
  "This was, by every available measure, a bad idea. It was also correct.",
  "The plan was simple. Swing a very long cable fast enough, and the tip moves faster than the rest of it. Much faster.",
  "The first attempt snapped the cable. The second attempt snapped the cable and a window. The third attempt was scheduled anyway.",
  "By the fourth trial, the tip was moving at close to three hundred metres a second. Sound manages three hundred and forty.",
  "Then it happened. The tip crossed the line, and the crack could be heard across the valley. The cows were not consulted.",
  "Here is why it works. A wave travelling down a tapering cable carries the same energy into less and less mass.",
  "Less mass with the same energy means more speed. By the end, the tip is moving faster than the sound it makes.",
  "The report described the result as a qualified success. The window was not qualified. It was replaced.",
  "And the engineer? He spent the rest of his career on bridges, which, he noted, do not crack. Usually.",
];

// Default 7 scenes: enough for cuts, a clip and captions, small enough to finish quickly.
NARRATION.splice(Number(process.env.DRYRUN_SCENES ?? 7));
console.log(`dry run: ${NARRATION.length} scenes, real espeak-ng speech, generated footage\n`);
const t0 = Date.now();

// ── speech, sentence by sentence, exactly the shape of timing data the real voice stage provides ──
const audio = NARRATION.map((text, i) => {
  const sentences = text.match(/[^.!?]+[.!?]+/g)!.map((s) => s.trim());
  const parts: string[] = [];
  const segments: { text: string; start: number; end: number }[] = [];
  let t = 0;
  for (const [k, s] of sentences.entries()) {
    const f = path.join(OUT, `a${i}-${k}.wav`);
    run("espeak-ng", ["-s", "165", "-w", f, s]);
    const d = dur(f);
    segments.push({ text: s, start: t, end: t + d });
    t += d;
    parts.push(f);
  }
  const file = path.join(OUT, `scene${i}.wav`);
  const list = path.join(OUT, `l${i}.txt`);
  fs.writeFileSync(list, parts.map((p) => `file '${p}'`).join("\n"));
  run("ffmpeg", ["-v", "error", "-y", "-f", "concat", "-safe", "0", "-i", list, "-ar", "24000", "-ac", "1", file]);
  return { sceneId: `sc${i}`, file, duration: dur(file), segments };
});

// ── footage: three distinct shots per scene; scene 4 gets a real moving clip ──
const patterns = ["testsrc2", "smptehdbars", "rgbtestsrc", "mandelbrot", "life"];
const images = NARRATION.map((_, i) => [0, 1, 2].map((k) => {
  if (i === Math.min(4, NARRATION.length - 1) && k === 0) {
    const f = path.join(OUT, `clip${i}.mp4`);
    run("ffmpeg", ["-v", "error", "-y", "-f", "lavfi", "-i", "testsrc2=size=1920x1080:rate=30:duration=8",
      "-c:v", "libx264", "-pix_fmt", "yuv420p", f]);
    return f;
  }
  const f = path.join(OUT, `img${i}-${k}.jpg`);
  const src = patterns[(i + k) % patterns.length]!;
  const spec = src === "life" ? "life=s=1920x1080:mold=10:r=1" : src === "mandelbrot" ? "mandelbrot=s=1920x1080" : `${src}=size=1920x1080`;
  run("ffmpeg", ["-v", "error", "-y", "-f", "lavfi", "-i", spec, "-frames:v", "1", "-q:v", "3", f]);
  return f;
}));
// The real beat sheet, so chapters are built from roles exactly as in production.
const ROLES = ["cold_open", "reaction", "premise", "escalation", "escalation", "turn", "mechanism", "mechanism", "payoff", "kicker"];
const scenes = NARRATION.map((narration, i) => ({ id: `sc${i}`, narration, role: ROLES[i]!, cardHeadline: i === 4 ? "300 m/s" : undefined }));

// The planner reports its own shot count; that, not a pixel-difference detector (which cannot tell
// apart test patterns sharing colour bars), is the source of truth for the cut rate.
const planned: number[] = [];
const origLog = console.log;
console.log = (...a: unknown[]) => { const m = /(\d+) shots across/.exec(String(a[0])); if (m) planned.push(Number(m[1])); origLog(...a); };
const prepSec = (Date.now() - t0) / 1000;

// ── the real render, long and Short ──
const r0 = Date.now();
const long = await renderVideo({ scenes, images, audio, dir: OUT, seed: 12, name: "dry-long",
  captions: scenes.map((s) => s.cardHeadline) });
const longSec = (Date.now() - r0) / 1000;
const s0 = Date.now();
const short = await renderVideo({ scenes: scenes.slice(0, 3), images: images.slice(0, 3), audio: audio.slice(0, 3),
  dir: OUT, seed: 13, size: VERTICAL, name: "dry-short", burnCaptions: true });
const shortSec = (Date.now() - s0) / 1000;

// ── measure ──
let bad = 0;
const check = (pass: boolean, what: string, detail: string) => { console.log(`${pass ? "✅" : "❌"} ${what} — ${detail}`); if (!pass) bad++; };
const speech = audio.reduce((n, a) => n + a.duration, 0);

for (const [label, file, secs, want, n] of [
  ["long", long.videoPath, longSec, [1920, 1080], NARRATION.length],
  ["Short", short.videoPath, shortSec, [1080, 1920], 3],
] as const) {
  console.log(`\n── ${label} ──`);
  const d = dur(file);
  const [w, h] = probe(file, "stream=width,height").slice(0, 2).map(Number);
  const spoken = audio.slice(0, n).reduce((x, a) => x + a.duration, 0);
  const cuts = run("ffmpeg", ["-v", "error", "-i", file, "-vf", "select='gt(scene,0.25)',metadata=print:file=-", "-f", "null", "-"])
    .split("\n").filter((l) => l.startsWith("frame:")).length;
  // ebur128 prints its summary to stderr; the integrated loudness is the last "I:" line.
  const loudLine = run("sh", ["-c", `ffmpeg -hide_banner -nostats -i "${file}" -af ebur128 -f null - 2>&1 | grep -E "^ +I:" | tail -1`]);
  const loud = Number(/(-?[\d.]+) LUFS/.exec(loudLine)?.[1] ?? NaN);
  const moov = run("sh", ["-c", `head -c 200000 "${file}" | grep -c moov || true`]).trim() !== "0";

  check(w === want[0] && h === want[1], "resolution", `${w}x${h}`);
  check(Math.abs(d - spoken) < Math.max(2, spoken * 0.06), "picture length matches the speech", `${d.toFixed(1)}s video vs ${spoken.toFixed(1)}s speech`);
  const shots = planned[label === "long" ? 0 : 1] ?? cuts + 1;
  const shotLen = d / shots;
  check(shotLen <= (label === "long" ? 8 : 5), "cut rate keeps the picture moving", `${shots} shots, one every ${shotLen.toFixed(1)}s (detector saw ${cuts} hard cuts)`);
  const kbps = Number(probe(file, "format=bit_rate")[0]) / 1000;
  // 10 Mbps ceiling + 192 kbps audio + a small allowance for per-clip buffer start-up.
  check(kbps <= 11_500, "bitrate stays under the ceiling", `${(kbps / 1000).toFixed(1)} Mbps (ceiling 10 Mbps video + audio)`);
  check(Math.abs(loud - -14) <= 1.5, "loudness at YouTube's target", `${loud.toFixed(1)} LUFS (target -14)`);
  check(moov, "fast-start: playable before fully downloaded", moov ? "moov atom at the front" : "moov atom at the end");
  check(secs < d * 6, "render speed leaves room inside CI limits", `${secs.toFixed(0)}s to render ${d.toFixed(0)}s (${(secs / d).toFixed(1)}x real time)`);
}

// captions: every cue after the fade-in, in order, none overlapping
const srt = fs.existsSync(short.srtPath ?? "") ? fs.readFileSync(short.srtPath!, "utf8") : "";
const cues = [...srt.matchAll(/(\d\d):(\d\d):(\d\d),(\d{3}) --> (\d\d):(\d\d):(\d\d),(\d{3})/g)]
  .map((m) => [+m[1]! * 3600 + +m[2]! * 60 + +m[3]! + +m[4]! / 1000, +m[5]! * 3600 + +m[6]! * 60 + +m[7]! + +m[8]! / 1000]);
console.log("\n── captions ──");
check(cues.length > 3, "captions were generated", `${cues.length} cues`);
check(cues.every(([a], i) => i === 0 || a >= cues[i - 1]![1]! - 0.01), "no two captions overlap", "checked every pair");
check((cues[0]?.[0] ?? 0) >= 0.3, "no caption over the opening fade", `first cue at ${cues[0]?.[0]?.toFixed(2)}s`);

// chapters, from real render timings, against YouTube's rules
console.log("\n── chapters ──");
const chapters = buildChapters(scenes as never, long.timings);
const secs = chapters.map((c) => { const [m, sec] = c.split(" ")[0]!.split(":").map(Number); return m! * 60 + sec!; });
if (chapters.length) {
  check(secs[0] === 0, "first chapter at 0:00", chapters[0]!);
  check(chapters.length >= 3, "at least three chapters", `${chapters.length}`);
  check(secs.every((t, i) => i === 0 || t - secs[i - 1]! >= 10), "every chapter at least 10 s", secs.join(", ") + " s");
  check(!chapters.some((c) => /part \d|step \d/i.test(c)), "no signposting titles", chapters.map((c) => c.slice(5)).join(" | "));
} else {
  // A 50-second test video cannot hold three 10-second chapters by design; that is correct behaviour.
  check(dur(long.videoPath) < 45, "chapters omitted only when the video is too short for three", `${dur(long.videoPath).toFixed(0)}s`);
}
for (const c of chapters) origLog(`   ${c}`);

// frames for a human to look at
run("ffmpeg", ["-v", "error", "-y", "-i", long.videoPath, "-vf", `fps=${(12 / dur(long.videoPath)).toFixed(4)},scale=480:-2,tile=4x3`, "-frames:v", "1", path.join(OUT, "contact-long.jpg")]);
run("ffmpeg", ["-v", "error", "-y", "-i", short.videoPath, "-vf", `fps=${(6 / dur(short.videoPath)).toFixed(4)},scale=240:-2,tile=6x1`, "-frames:v", "1", path.join(OUT, "contact-short.jpg")]);

console.log(`\nprep ${prepSec.toFixed(0)}s · render long ${longSec.toFixed(0)}s · Short ${shortSec.toFixed(0)}s · speech ${speech.toFixed(0)}s`);
console.log(`frames saved: ${OUT}/contact-long.jpg and contact-short.jpg`);
console.log(bad ? `\n❌ ${bad} production check(s) failed.` : "\n✅ the render engine produces a correct video.");
process.exitCode = bad ? 1 : 0;
export {};
